### ISSUE TITLE
Add me as a collaborator

### ISSUE THREAD

**Issue by olekslitus** [Ryanjso/DS3500-Final-NEU-FALL-2021#1]

**Comment by Ryanjso** [comment]
<img width="934" alt="Screen Shot 2021-10-13 at 11 14 11 AM" src="https://user-images.githubusercontent.com/39172778/137162267-39fe10f6-f8c7-4135-96c9-c86ed26738a1.png">
I believe so

**Comment by orreksu** [comment]
Great.
