### ISSUE TITLE
Please provide feedback on our project

### ISSUE THREAD

**Issue by Ryanjso** [Ryanjso/DS3500-Final-NEU-FALL-2021#11]
"Add a task in your git repo assigning the TA to provide feedback."
https://www.gradescope.com/courses/306728/assignments/1636683/submissions/new

Thank you!

**Comment by orreksu** [comment]
Hello guys. Sorry for the late feedback, I got smashed with my homework.
You had a good progress and structured things nicely. Continue doing so.
You should really start working on the AI, as it is critical to the project.
